/*
 * k_port_x86_iamcu_defs.h
 *
 *  Created on: May 10, 2017
 *      Author: vntfene
 */

#ifndef ULIPERTOSPICO_INCLUDE_ARCH_INTEL_QUARK_SE_C1000_K_PORT_X86_IAMCU_DEFS_H_
#define ULIPERTOSPICO_INCLUDE_ARCH_INTEL_QUARK_SE_C1000_K_PORT_X86_IAMCU_DEFS_H_



#endif /* ULIPERTOSPICO_INCLUDE_ARCH_INTEL_QUARK_SE_C1000_K_PORT_X86_IAMCU_DEFS_H_ */
